### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [MSWS/CSC101#1]
Hey MSWS!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by MSWS** [comment]
Hi assignguard, on whose behalf are you contacting me? Could you provide the filenames or lines of code that are specifically infringing copyright law?

As for institutional academic integrity, I will not remove any code purely for that purpose. My code is intentionally public to allow for both a portfolio of my work, for others to benefit and contribute, and as a simpler method of archiving. This is effectively the same as going to StackOverflow and finding questions on there.
